version: "3.9"
services:
  docker-cron:
    build:
      context: .
    image: docker-cron
    container_name: docker-cron
    environment:
      - TZ=${TZ:-America/Toronto}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - docker-cron:/cron
    
volumes:
  docker-cron:
    name: docker_cron
    driver: local